[project]
name = "tp-info-quantique"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "pylatexenc>=2.10",
    "python-dotenv>=1.0.1",
    "qiskit>=1.4.1",
    "qiskit-ibm-runtime>=0.37.0",
]
